#[derive(Debug, Clone)]
struct VmLocalState {
    scene: String,
    lexer: SceneLexer,
    stack: IfcStack,
    frames: Vec<Frame>,
    scene_title: String,
    user_prop_forms: Vec<i32>,
    user_prop_values: Vec<PropValue>,
    frame_action: FrameAction,
    frame_action_ch: Vec<FrameAction>,
    excall_frame_action: FrameAction,
    excall_frame_action_ch: Vec<FrameAction>,
    key_wait_proc: KeyWaitProc,
    group_wait_proc: GroupWaitProc,
    // C++ cmd_call.cpp excall allocation state (`excall.is_excall/check_alloc`).
    excall_allocated: [bool; 2],
    flags_a: Vec<i32>,
    flags_b: Vec<i32>,
    flags_c: Vec<i32>,
    flags_d: Vec<i32>,
    flags_e: Vec<i32>,
    flags_f: Vec<i32>,
    excall_flags_f: [Vec<i32>; 2],
    flags_x: Vec<i32>,
    flags_g: Vec<i32>,
    flags_z: Vec<i32>,
    flags_s: Vec<String>,
    flags_m: Vec<String>,
    global_namae: Vec<String>,
    local_namae: Vec<String>,
    save_point_set: bool,
    sel_point_set: bool,
    save_point_snapshot: Option<VmPersistentState>,
    sel_point_snapshot: Option<VmPersistentState>,
    sel_point_stock: Option<VmPersistentState>,
    cur_mwnd_element: Vec<i32>,
    cur_sel_mwnd_element: Vec<i32>,
    last_sel_msg: String,
    hide_mwnd_onoff_flag: i32,
    hide_mwnd_enable_flag: i32,
    hide_mwnd_exist_flag: i32,
    read_skip_onoff_flag: i32,
    read_skip_enable_flag: i32,
    read_skip_exist_flag: i32,
    auto_mode_onoff_flag: i32,
    auto_mode_enable_flag: i32,
    auto_mode_exist_flag: i32,
    msg_back_enable_flag: i32,
    msg_back_exist_flag: i32,
    msg_back_open_flag: i32,
    msg_back_has_message: i32,
    msg_back_disable_flag: i32,
    msg_back_off_flag: i32,
    msg_back_disp_off_flag: i32,
    msg_back_proc_off_flag: i32,
    return_to_sel_enable_flag: i32,
    return_to_sel_exist_flag: i32,
    return_to_menu_enable_flag: i32,
    return_to_menu_exist_flag: i32,
    save_enable_flag: i32,
    save_exist_flag: i32,
    load_enable_flag: i32,
    load_exist_flag: i32,
    end_game_enable_flag: i32,
    end_game_exist_flag: i32,
    game_end_flag: i32,
    game_end_no_warning_flag: i32,
    game_end_save_done_flag: i32,
    syscom_cfg: VmSyscomConfigState,
    no_wipe_anime_onoff_flag: i32,
    skip_wipe_anime_onoff_flag: i32,
    script_skip_unread_message_flag: i32,
    script_stage_time_stop_flag: i32,
    system_wipe_flag: i32,
    do_frame_action_flag: i32,
    do_load_after_call_flag: i32,
    game_timer_move_flag: i32,
    syscom_menu_disable_flag: i32,
    last_pc: usize,
    last_line_no: i32,
    last_scene: String,
    proc_stack: Vec<VmProcType>,
    script_dont_set_save_point: bool,
    script_skip_disable: bool,
    script_ctrl_disable: bool,
    script_not_stop_skip_by_click: bool,
    script_not_skip_msg_by_click: bool,
    script_auto_mode_flag: bool,
    script_auto_mode_moji_wait: i32,
    script_auto_mode_min_wait: i32,
    script_auto_mode_moji_cnt: i32,
    script_mouse_cursor_hide_onoff: i32,
    script_mouse_cursor_hide_time: i32,
    script_msg_speed: i32,
    script_msg_nowait: bool,
    script_async_msg_mode: bool,
    script_async_msg_mode_once: bool,
    script_hide_mwnd_disable: bool,
    script_cursor_disp_off: bool,
    script_cursor_move_by_key_disable: bool,
    script_key_disable: [bool; 256],
    script_mwnd_anime_off_flag: bool,
    script_mwnd_anime_on_flag: bool,
    script_mwnd_disp_off_flag: bool,
    script_koe_dont_stop_on_flag: bool,
    script_koe_dont_stop_off_flag: bool,
    script_shortcut_disable: bool,
    script_quake_stop_flag: bool,
    script_emote_mouth_stop_flag: bool,
    script_bgmfade_flag: bool,
    script_vsync_wait_off_flag: bool,
    script_skip_trigger: bool,
    script_ignore_r_flag: bool,
    script_cursor_no: i32,
    script_time_stop_flag: bool,
    script_counter_time_stop_flag: bool,
    script_frame_action_time_stop_flag: bool,
    script_font_name: String,
    script_font_bold: i32,
    script_font_shadow: i32,
    script_allow_joypad_mode_onoff: i32,
    excall_script_font_name: [String; 2],
    excall_script_font_bold: [i32; 2],
    excall_script_font_shadow: [i32; 2],
    counter_list_size: usize,
    excall_counter_list_size: [usize; 2],
    counter_values: Vec<i32>,
    counter_active: Vec<bool>,
    database_tables: Vec<Vec<Vec<PropValue>>>,
    database_row_calls: Vec<Vec<i32>>,
    database_col_calls: Vec<Vec<i32>>,
    database_col_types: Vec<Vec<u8>>,
    cg_table_off_flag: bool,
    cg_flags: Vec<i32>,
    cg_name_to_flag: BTreeMap<String, i32>,
    cg_group_codes: Vec<[i32; 5]>,
    cg_code_exist_cnt: Vec<i32>,
    bgm_name_listened: BTreeMap<String, bool>,
    g00buf_loaded: Vec<Option<String>>,
    mask_slots: Vec<MaskSlotState>,
    object_gan_loaded_path: BTreeMap<(i32, i32, i32), String>,
    object_gan_started_set: BTreeMap<(i32, i32, i32), i32>,
}

