#[derive(Debug, Clone)]
pub(super) struct VmSyscomConfigState {
    pub(super) window_mode: i32,
    pub(super) window_mode_size: i32,
    pub(super) saveload_alert_onoff: i32,
    pub(super) no_mwnd_anime_onoff: i32,
    pub(super) filter_color: [i32; 4],
    pub(super) font_name: String,
    pub(super) font_bold: i32,
    pub(super) font_decoration: i32,
    pub(super) bgm_volume: i32,
    pub(super) koe_volume: i32,
    pub(super) pcm_volume: i32,
    pub(super) se_volume: i32,
    pub(super) bgm_onoff: i32,
    pub(super) koe_onoff: i32,
    pub(super) pcm_onoff: i32,
    pub(super) se_onoff: i32,
    pub(super) all_volume: i32,
    pub(super) message_speed: i32,
    pub(super) message_nowait: i32,
    pub(super) auto_mode_moji_wait: i32,
    pub(super) auto_mode_min_wait: i32,
    pub(super) all_onoff: i32,
    pub(super) mwnd_btn_enabled: i32,
    pub(super) mwnd_btn_touch_enabled: i32,
    pub(super) global_extra_switch_onoff: std::collections::BTreeMap<i32, i32>,
    pub(super) global_extra_mode_values: std::collections::BTreeMap<i32, i32>,
    pub(super) object_disp_onoff: std::collections::BTreeMap<i32, i32>,
    pub(super) local_extra_mode_values: std::collections::BTreeMap<i32, i32>,
    pub(super) local_extra_mode_enable_flags: std::collections::BTreeMap<i32, i32>,
    pub(super) local_extra_mode_exist_flags: std::collections::BTreeMap<i32, i32>,
    pub(super) local_extra_switch_onoff_flags: std::collections::BTreeMap<i32, i32>,
    pub(super) local_extra_switch_enable_flags: std::collections::BTreeMap<i32, i32>,
    pub(super) local_extra_switch_exist_flags: std::collections::BTreeMap<i32, i32>,
    pub(super) bgmfade_volume: i32,
    pub(super) bgmfade_onoff: i32,
    pub(super) koemode: i32,
    pub(super) charakoe_onoff: std::collections::BTreeMap<i32, i32>,
    pub(super) charakoe_volume: std::collections::BTreeMap<i32, i32>,
    pub(super) jitan_speed: i32,
    pub(super) jitan_normal_onoff: i32,
    pub(super) jitan_auto_mode_onoff: i32,
    pub(super) jitan_koe_replay_onoff: i32,
    pub(super) sleep_onoff: i32,
    pub(super) wheel_next_message_onoff: i32,
    pub(super) koe_dont_stop_onoff: i32,
    pub(super) skip_unread_message_onoff: i32,
}

impl Default for VmSyscomConfigState {
    fn default() -> Self {
        Self {
            window_mode: 0,
            window_mode_size: 0,
            saveload_alert_onoff: 0,
            no_mwnd_anime_onoff: 0,
            filter_color: [0, 0, 0, 0],
            font_name: String::new(),
            font_bold: -1,
            font_decoration: -1,
            bgm_volume: 100,
            koe_volume: 100,
            pcm_volume: 100,
            se_volume: 100,
            bgm_onoff: 1,
            koe_onoff: 1,
            pcm_onoff: 1,
            se_onoff: 1,
            all_volume: 100,
            message_speed: -1,
            message_nowait: 0,
            auto_mode_moji_wait: -1,
            auto_mode_min_wait: -1,
            all_onoff: 1,
            mwnd_btn_enabled: 1,
            mwnd_btn_touch_enabled: 1,
            global_extra_switch_onoff: std::collections::BTreeMap::new(),
            global_extra_mode_values: std::collections::BTreeMap::new(),
            object_disp_onoff: std::collections::BTreeMap::new(),
            local_extra_mode_values: std::collections::BTreeMap::new(),
            local_extra_mode_enable_flags: std::collections::BTreeMap::new(),
            local_extra_mode_exist_flags: std::collections::BTreeMap::new(),
            local_extra_switch_onoff_flags: std::collections::BTreeMap::new(),
            local_extra_switch_enable_flags: std::collections::BTreeMap::new(),
            local_extra_switch_exist_flags: std::collections::BTreeMap::new(),
            bgmfade_volume: 255,
            bgmfade_onoff: 1,
            koemode: 0,
            charakoe_onoff: std::collections::BTreeMap::new(),
            charakoe_volume: std::collections::BTreeMap::new(),
            jitan_speed: 0,
            jitan_normal_onoff: 0,
            jitan_auto_mode_onoff: 0,
            jitan_koe_replay_onoff: 0,
            sleep_onoff: 0,
            wheel_next_message_onoff: 0,
            koe_dont_stop_onoff: 0,
            skip_unread_message_onoff: 0,
        }
    }
}
