// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_ALLEVENT_END: i32 = 0; // end
pub const ELM_ALLEVENT_WAIT: i32 = 1; // wait
pub const ELM_ALLEVENT_CHECK: i32 = 2; // check
