pub const ELM_BGM_GET_REGIST_NAME: i32 = 19;
pub const ELM_BGM_PLAY_ONESHOT: i32 = 1;

pub fn is_get_regist_name(elm: i32) -> bool {
    elm == crate::elm::bgm::ELM_BGM_GET_REGIST_NAME
}

pub fn is_play_oneshot(elm: i32) -> bool {
    elm == crate::elm::bgm::ELM_BGM_PLAY_ONESHOT
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_BGM_PLAY: i32 = 0; // play
pub const ELM_BGM_PLAY_WAIT: i32 = 2; // play_wait
pub const ELM_BGM_WAIT: i32 = 3; // wait
pub const ELM_BGM_STOP: i32 = 4; // stop
pub const ELM_BGM_WAIT_FADE: i32 = 5; // wait_fade
pub const ELM_BGM_SET_VOLUME: i32 = 6; // set_volume
pub const ELM_BGM_SET_VOLUME_MAX: i32 = 7; // set_volume_max
pub const ELM_BGM_SET_VOLUME_MIN: i32 = 8; // set_volume_min
pub const ELM_BGM_GET_VOLUME: i32 = 9; // get_volume
pub const ELM_BGM_PAUSE: i32 = 10; // pause
pub const ELM_BGM_RESUME: i32 = 11; // resume
pub const ELM_BGM_RESUME_WAIT: i32 = 12; // resume_wait
pub const ELM_BGM_GET_PLAY_POS: i32 = 13; // get_play_pos
pub const ELM_BGM_WAIT_KEY: i32 = 14; // wait_key
pub const ELM_BGM_WAIT_FADE_KEY: i32 = 15; // wait_fade_key
pub const ELM_BGM_READY: i32 = 16; // ready
pub const ELM_BGM_READY_ONESHOT: i32 = 17; // ready_oneshot
pub const ELM_BGM_CHECK: i32 = 18; // check
