pub const ELM_BGMTABLE_SET_ALL_FLAG: i32 = 4;

pub fn is_set_all_flag(elm: i32) -> bool {
    elm == crate::elm::bgmtable::ELM_BGMTABLE_SET_ALL_FLAG
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_BGMTABLE_GET_BGM_CNT: i32 = 0; // get_bgm_cnt
pub const ELM_BGMTABLE_GET_LISTEN_BY_NAME: i32 = 1; // get_listen_by_name
pub const ELM_BGMTABLE_SET_LISTEN_BY_NAME: i32 = 2; // set_listen_by_name
