// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_BTNSELITEMLIST_ARRAY: i32 = 0; // array
pub const ELM_BTNSELITEMLIST_ALLOC: i32 = 1; // alloc
pub const ELM_BTNSELITEMLIST_FREE: i32 = 2; // free
