pub const ELM_CALL_K: i32 = 1;
pub const ELM_CALL_L: i32 = 0;

pub fn is_cur_call(head: i32) -> bool {
    head == crate::elm::global::ELM_GLOBAL_CUR_CALL
}

pub fn is_call_l(head: i32) -> bool {
    head == crate::elm::call::ELM_CALL_L
}

pub fn is_call_k(head: i32) -> bool {
    head == crate::elm::call::ELM_CALL_K
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_CALLLIST_ARRAY: i32 = 0; // array
