pub const ELM_CGTABLE_GET_FLAG_NO_BY_NAME: i32 = 1;
pub const ELM_CGTABLE_SET_ALL_FLAG: i32 = 9;

pub fn is_get_flag_no_by_name(elm: i32) -> bool {
    elm == crate::elm::cgtable::ELM_CGTABLE_GET_FLAG_NO_BY_NAME
}

pub fn is_set_all_flag(elm: i32) -> bool {
    elm == crate::elm::cgtable::ELM_CGTABLE_SET_ALL_FLAG
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_CGTABLE_FLAG: i32 = 0; // flag
pub const ELM_CGTABLE_GET_LOOK_BY_NAME: i32 = 2; // get_look_by_name
pub const ELM_CGTABLE_SET_LOOK_BY_NAME: i32 = 3; // set_look_by_name
pub const ELM_CGTABLE_GET_CG_CNT: i32 = 4; // get_cg_cnt
pub const ELM_CGTABLE_GET_LOOK_CNT: i32 = 5; // get_look_cnt
pub const ELM_CGTABLE_GET_LOOK_PERCENT: i32 = 6; // get_look_percent
pub const ELM_CGTABLE_SET_DISABLE: i32 = 7; // set_disable
pub const ELM_CGTABLE_SET_ENABLE: i32 = 8; // set_enable
pub const ELM_CGTABLE_GET_NAME_BY_FLAG_NO: i32 = 10; // get_name_by_flag_no
