// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_COUNTER_SET: i32 = 0; // set
pub const ELM_COUNTER_GET: i32 = 1; // get
pub const ELM_COUNTER_RESET: i32 = 2; // reset
pub const ELM_COUNTER_START: i32 = 3; // start
pub const ELM_COUNTER_STOP: i32 = 4; // stop
pub const ELM_COUNTER_RESUME: i32 = 5; // resume
pub const ELM_COUNTER_WAIT: i32 = 6; // wait
pub const ELM_COUNTER_CHECK_VALUE: i32 = 7; // check_value
pub const ELM_COUNTER_WAIT_KEY: i32 = 8; // wait_key
pub const ELM_COUNTER_START_REAL: i32 = 9; // start_real
pub const ELM_COUNTER_START_FRAME: i32 = 10; // start_frame
pub const ELM_COUNTER_START_FRAME_REAL: i32 = 11; // start_frame_real
pub const ELM_COUNTER_START_FRAME_LOOP: i32 = 12; // start_frame_loop
pub const ELM_COUNTER_START_FRAME_LOOP_REAL: i32 = 13; // start_frame_loop_real
pub const ELM_COUNTER_CHECK_ACTIVE: i32 = 14; // check_active
