pub const ELM_DATABASELIST_GET_SIZE: i32 = 1;

pub fn is_get_size(elm: i32) -> bool {
    elm == crate::elm::databaselist::ELM_DATABASELIST_GET_SIZE
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_DATABASE_GET_NUM: i32 = 0; // get_num
pub const ELM_DATABASE_GET_STR: i32 = 1; // get_str
pub const ELM_DATABASE_GET_DATA: i32 = 2; // get_data
pub const ELM_DATABASE_CHECK_ITEM: i32 = 3; // check_item
pub const ELM_DATABASE_CHECK_COLUMN: i32 = 4; // check_column
pub const ELM_DATABASE_FIND_NUM: i32 = 5; // find_num
pub const ELM_DATABASE_FIND_STR: i32 = 6; // find_str
pub const ELM_DATABASE_FIND_STR_REAL: i32 = 7; // find_str_real
pub const ELM_DATABASELIST_ARRAY: i32 = 0; // array
