pub const ELM_EDITBOX_GET_TEXT: i32 = 3;

pub fn is_get_text(elm: i32) -> bool {
    elm == crate::elm::editbox::ELM_EDITBOX_GET_TEXT
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_EDITBOX_CREATE: i32 = 0; // create
pub const ELM_EDITBOX_DESTROY: i32 = 1; // destroy
pub const ELM_EDITBOX_SET_TEXT: i32 = 2; // set_text
pub const ELM_EDITBOX_CHECK_DECIDED: i32 = 4; // check_decided
pub const ELM_EDITBOX_CHECK_CANCELED: i32 = 5; // check_canceled
pub const ELM_EDITBOX_SET_FOCUS: i32 = 6; // set_focus
pub const ELM_EDITBOX_CLEAR_INPUT: i32 = 7; // clear_input
pub const ELM_EDITBOXLIST_ARRAY: i32 = 0; // array
pub const ELM_EDITBOXLIST_CLEAR_INPUT: i32 = 1; // clear_input
