// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_EFFECTLIST_ARRAY: i32 = 0; // array
pub const ELM_EFFECTLIST_RESIZE: i32 = 1; // resize
pub const ELM_EFFECTLIST_GET_SIZE: i32 = 2; // get_size
