// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_EXCALL_STAGE: i32 = 0; // stage
pub const ELM_EXCALL_FRONT: i32 = 1; // front
pub const ELM_EXCALL_BACK: i32 = 2; // back
pub const ELM_EXCALL_NEXT: i32 = 3; // next
pub const ELM_EXCALL_ALLOC: i32 = 4; // alloc
pub const ELM_EXCALL_FREE: i32 = 5; // free
pub const ELM_EXCALL_COUNTER: i32 = 6; // counter
pub const ELM_EXCALL_F: i32 = 7; // f
pub const ELM_EXCALL_CHECK_ALLOC: i32 = 8; // check_alloc
pub const ELM_EXCALL_FRAME_ACTION: i32 = 9; // frame_action
pub const ELM_EXCALL_FRAME_ACTION_CH: i32 = 10; // frame_action_ch
pub const ELM_EXCALL_ARRAY: i32 = 11; // array
pub const ELM_EXCALL_IS_EXCALL: i32 = 12; // is_excall
pub const ELM_EXCALL_SCRIPT: i32 = 13; // script
