pub const ELM_FRAMEACTIONLIST_GET_SIZE: i32 = 2;
pub const ELM_FRAMEACTIONLIST_RESIZE: i32 = 1;
pub const ELM_FRAMEACTION_END: i32 = 2;
pub const ELM_FRAMEACTION_IS_END_ACTION: i32 = 4;
pub const ELM_FRAMEACTION_START: i32 = 1;
pub const ELM_FRAMEACTION_START_REAL: i32 = 3;

pub fn is_frameactionlist_get_size(method: i32) -> bool {
    method == crate::elm::frameaction::ELM_FRAMEACTIONLIST_GET_SIZE
}

pub fn is_frameactionlist_resize(method: i32) -> bool {
    method == crate::elm::frameaction::ELM_FRAMEACTIONLIST_RESIZE
}

pub fn is_frameaction_start(method: i32) -> bool {
    method == crate::elm::frameaction::ELM_FRAMEACTION_START
        || method == crate::elm::frameaction::ELM_FRAMEACTION_START_REAL
}

pub fn is_frameaction_start_real(method: i32) -> bool {
    method == crate::elm::frameaction::ELM_FRAMEACTION_START_REAL
}

pub fn is_frameaction_end(method: i32) -> bool {
    method == crate::elm::frameaction::ELM_FRAMEACTION_END
}

pub fn is_frameaction_is_end_action(method: i32) -> bool {
    method == crate::elm::frameaction::ELM_FRAMEACTION_IS_END_ACTION
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_FRAMEACTION_COUNTER: i32 = 0; // counter
pub const ELM_FRAMEACTIONLIST_ARRAY: i32 = 0; // array
