// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_G00BUFLIST_FREE_ALL: i32 = 0; // free_all
pub const ELM_G00BUFLIST_ARRAY: i32 = 1; // array
pub const ELM_G00BUFLIST_GET_SIZE: i32 = 2; // get_size
