// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_GROUP_SEL: i32 = 0; // sel
pub const ELM_GROUP_SEL_CANCEL: i32 = 1; // sel_cancel
pub const ELM_GROUP_START: i32 = 2; // start
pub const ELM_GROUP_GET_DECIDED_NO: i32 = 3; // get_decided_no
pub const ELM_GROUP_INIT: i32 = 4; // init
pub const ELM_GROUP_END: i32 = 5; // end
pub const ELM_GROUP_GET_HIT_NO: i32 = 6; // get_hit_no
pub const ELM_GROUP_GET_PUSHED_NO: i32 = 7; // get_pushed_no
pub const ELM_GROUP_ORDER: i32 = 8; // order
pub const ELM_GROUP_ON_HIT_NO: i32 = 9; // on_hit_no
pub const ELM_GROUP_START_CANCEL: i32 = 10; // start_cancel
pub const ELM_GROUP_ON_PUSHED_NO: i32 = 11; // on_pushed_no
pub const ELM_GROUP_ON_DECIDED_NO: i32 = 12; // on_decided_no
pub const ELM_GROUP_LAYER: i32 = 13; // layer
pub const ELM_GROUP_CANCEL_PRIORITY: i32 = 14; // cancel_priority
pub const ELM_GROUP_GET_RESULT: i32 = 15; // get_result
pub const ELM_GROUP_GET_RESULT_BUTTON_NO: i32 = 16; // get_result_button_no
