pub const ELM_INPUT_CANCEL: i32 = 1;
pub const ELM_INPUT_CLEAR: i32 = 2;
pub const ELM_INPUT_DECIDE: i32 = 0;
pub const ELM_INPUT_NEXT: i32 = 3;

pub fn is_clear_or_next(elm: i32) -> bool {
    elm == crate::elm::input::ELM_INPUT_NEXT || elm == crate::elm::input::ELM_INPUT_CLEAR
}

pub fn is_decide_or_cancel(elm: i32) -> bool {
    elm == crate::elm::input::ELM_INPUT_DECIDE || elm == crate::elm::input::ELM_INPUT_CANCEL
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_INPUT_KEY: i32 = 0; // key
pub const ELM_INPUT_WAIT: i32 = 4; // wait
pub const ELM_INPUT_WAIT_FORCE: i32 = 5; // wait_force
pub const ELM_INPUT_UP: i32 = 6; // up
pub const ELM_INPUT_DOWN: i32 = 7; // down
pub const ELM_INPUT_LEFT: i32 = 8; // left
pub const ELM_INPUT_RIGHT: i32 = 9; // right
pub const ELM_INPUT__GET_LAST_DEVICE_TYPE: i32 = 10; // __get_last_device_type
