pub const ELM_INTEVENT_CHECK: i32 = 5;

pub fn is_check(elm: i32) -> bool {
    elm == crate::elm::intevent::ELM_INTEVENT_CHECK
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_INTEVENT_SET: i32 = 0; // set
pub const ELM_INTEVENT_LOOP: i32 = 1; // loop
pub const ELM_INTEVENT_TURN: i32 = 2; // turn
pub const ELM_INTEVENT_END: i32 = 3; // end
pub const ELM_INTEVENT_WAIT: i32 = 4; // wait
pub const ELM_INTEVENT__SET: i32 = 6; // __set
pub const ELM_INTEVENT_SET_REAL: i32 = 7; // set_real
pub const ELM_INTEVENT_LOOP_REAL: i32 = 8; // loop_real
pub const ELM_INTEVENT_TURN_REAL: i32 = 9; // turn_real
pub const ELM_INTEVENT_WAIT_KEY: i32 = 10; // wait_key
pub const ELM_INTEVENT_YURE: i32 = 11; // yure
pub const ELM_INTEVENT_YURE_REAL: i32 = 12; // yure_real
pub const ELM_INTEVENT_GET_EVENT_VALUE: i32 = 13; // get_event_value
pub const ELM_INTEVENTLIST_ARRAY: i32 = 0; // array
pub const ELM_INTEVENTLIST_RESIZE: i32 = 1; // resize
