// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_JOYPAD_KEY: i32 = 0; // key
pub const ELM_JOYPAD_LEFT_STICK: i32 = 1; // left_stick
pub const ELM_JOYPAD_RIGHT_STICK: i32 = 2; // right_stick
pub const ELM_JOYPAD_LEFT_TRIGGER: i32 = 3; // left_trigger
pub const ELM_JOYPAD_RIGHT_TRIGGER: i32 = 4; // right_trigger
