// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_KEYBOARD_KEY: i32 = 0; // key
pub const ELM_KEYBOARD_CLEAR: i32 = 1; // clear
pub const ELM_KEYBOARD_NEXT: i32 = 2; // next
