pub const ELM_INTLISTREF_CLEAR: i32 = 8;
pub const ELM_INTLISTREF_GET_SIZE: i32 = 9;
pub const ELM_INTLISTREF_RESIZE: i32 = 2;
pub const ELM_INTLISTREF_SETS: i32 = 1;
pub const ELM_INTLIST_CLEAR: i32 = 8;
pub const ELM_INTLIST_GET_SIZE: i32 = 9;
pub const ELM_INTLIST_INIT: i32 = 10;
pub const ELM_INTLIST_RESIZE: i32 = 2;
pub const ELM_INTLIST_SETS: i32 = 1;
pub const ELM_STRLIST_GET_SIZE: i32 = 4;
pub const ELM_STRLIST_INIT: i32 = 3;
pub const ELM_STRLIST_RESIZE: i32 = 2;

pub fn is_intlist_get_size(method: i32) -> bool {
    method == crate::elm::list::ELM_INTLIST_GET_SIZE
        || method == crate::elm::list::ELM_INTLISTREF_GET_SIZE
}

pub fn is_intlist_init(method: i32) -> bool {
    method == crate::elm::list::ELM_INTLIST_INIT
}

pub fn is_intlist_resize(method: i32) -> bool {
    method == crate::elm::list::ELM_INTLIST_RESIZE
        || method == crate::elm::list::ELM_INTLISTREF_RESIZE
}

pub fn is_intlist_sets(method: i32) -> bool {
    method == crate::elm::list::ELM_INTLIST_SETS || method == crate::elm::list::ELM_INTLISTREF_SETS
}

pub fn is_intlist_clear(method: i32) -> bool {
    method == crate::elm::list::ELM_INTLIST_CLEAR
        || method == crate::elm::list::ELM_INTLISTREF_CLEAR
}

pub fn is_strlist_get_size(method: i32) -> bool {
    method == crate::elm::list::ELM_STRLIST_GET_SIZE
}

pub fn is_strlist_init(method: i32) -> bool {
    method == crate::elm::list::ELM_STRLIST_INIT
}

pub fn is_strlist_resize(method: i32) -> bool {
    method == crate::elm::list::ELM_STRLIST_RESIZE
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_INTLIST_ARRAY: i32 = 0; // array
pub const ELM_INTLIST_BIT: i32 = 3; // bit
pub const ELM_INTLIST_BIT2: i32 = 4; // bit2
pub const ELM_INTLIST_BIT4: i32 = 5; // bit4
pub const ELM_INTLIST_BIT16: i32 = 6; // bit16
pub const ELM_INTLIST_BIT8: i32 = 7; // bit8
pub const ELM_INTLISTREF_ARRAY: i32 = 0; // array
pub const ELM_INTLISTREF_BIT: i32 = 3; // bit
pub const ELM_INTLISTREF_BIT2: i32 = 4; // bit2
pub const ELM_INTLISTREF_BIT4: i32 = 5; // bit4
pub const ELM_INTLISTREF_BIT16: i32 = 6; // bit16
pub const ELM_INTLISTREF_BIT8: i32 = 7; // bit8
pub const ELM_STR_UPPER: i32 = 0; // upper
pub const ELM_STR_LOWER: i32 = 1; // lower
pub const ELM_STR_LEFT: i32 = 2; // left
pub const ELM_STR_MID: i32 = 3; // mid
pub const ELM_STR_RIGHT: i32 = 4; // right
pub const ELM_STR_LEN: i32 = 5; // len
pub const ELM_STR_CNT: i32 = 6; // cnt
pub const ELM_STR_LEFT_LEN: i32 = 7; // left_len
pub const ELM_STR_MID_LEN: i32 = 8; // mid_len
pub const ELM_STR_RIGHT_LEN: i32 = 9; // right_len
pub const ELM_STR_SEARCH: i32 = 10; // search
pub const ELM_STR_SEARCH_LAST: i32 = 11; // search_last
pub const ELM_STR_TONUM: i32 = 12; // tonum
pub const ELM_STR_GET_CODE: i32 = 13; // get_code
pub const ELM_STRLIST_ARRAY: i32 = 0; // array
pub const ELM_STRLIST_SETS: i32 = 1; // sets
pub const ELM_KEY_GET_FLICK_ANGLE: i32 = 0; // get_flick_angle
pub const ELM_KEY_ON_DOWN: i32 = 1; // on_down
pub const ELM_KEY_ON_UP: i32 = 4; // on_up
pub const ELM_KEY_ON_DOWN_UP: i32 = 5; // on_down_up
pub const ELM_KEY_IS_DOWN: i32 = 6; // is_down
pub const ELM_KEY_IS_UP: i32 = 7; // is_up
pub const ELM_KEY_ON_FLICK: i32 = 10; // on_flick
pub const ELM_KEY_GET_FLICK_PIXEL: i32 = 14; // get_flick_pixel
pub const ELM_KEY_GET_FLICK_MM: i32 = 15; // get_flick_mm
pub const ELM_KEY_ON_REPEAT: i32 = 16; // on_repeat
pub const ELM_KEYLIST__WAIT: i32 = 0; // __wait
pub const ELM_KEYLIST_WAIT: i32 = 0; // wait
pub const ELM_KEYLIST__WAIT_FORCE: i32 = 1; // __wait_force
pub const ELM_KEYLIST_WAIT_FORCE: i32 = 1; // wait_force
pub const ELM_KEYLIST_ARRAY: i32 = 2; // array
pub const ELM_KEYLIST__CLEAR: i32 = 3; // __clear
pub const ELM_KEYLIST_CLEAR: i32 = 3; // clear
pub const ELM_KEYLIST__NEXT: i32 = 5; // __next
pub const ELM_KEYLIST_NEXT: i32 = 5; // next
