// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_MASK_CREATE: i32 = 0; // create
pub const ELM_MASK_INIT: i32 = 1; // init
pub const ELM_MASK_X_EVE: i32 = 2; // x_eve
pub const ELM_MASK_Y_EVE: i32 = 3; // y_eve
pub const ELM_MASK_X: i32 = 4; // x
pub const ELM_MASK_Y: i32 = 5; // y
