pub const ELM_MATH_ABS: i32 = 5;
pub const ELM_MATH_ARCTAN: i32 = 18;
pub const ELM_MATH_COS: i32 = 7;
pub const ELM_MATH_LIMIT: i32 = 10;
pub const ELM_MATH_MAX: i32 = 3;
pub const ELM_MATH_MIN: i32 = 4;
pub const ELM_MATH_RAND: i32 = 0;
pub const ELM_MATH_SIN: i32 = 6;
pub const ELM_MATH_SQRT: i32 = 14;

pub fn is_abs(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_ABS
}
pub fn is_min(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_MIN
}
pub fn is_max(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_MAX
}
pub fn is_rand(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_RAND
}
pub fn is_limit(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_LIMIT
}
pub fn is_sqrt(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_SQRT
}
pub fn is_sin(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_SIN
}
pub fn is_cos(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_COS
}
pub fn is_arctan(method: i32) -> bool {
    method == crate::elm::math::ELM_MATH_ARCTAN
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_MATH_TOSTR: i32 = 1; // tostr
pub const ELM_MATH_TIMETABLE: i32 = 2; // timetable
pub const ELM_MATH_TAN: i32 = 8; // tan
pub const ELM_MATH_LINEAR: i32 = 9; // linear
pub const ELM_MATH_TOSTR_ZERO: i32 = 11; // tostr_zero
pub const ELM_MATH_TOSTR_ZEN: i32 = 12; // tostr_zen
pub const ELM_MATH_TOSTR_ZEN_ZERO: i32 = 13; // tostr_zen_zero
pub const ELM_MATH_DISTANCE: i32 = 15; // distance
pub const ELM_MATH_ARCSIN: i32 = 16; // arcsin
pub const ELM_MATH_ARCCOS: i32 = 17; // arccos
pub const ELM_MATH_LOG: i32 = 19; // log
pub const ELM_MATH_LOG2: i32 = 20; // log2
pub const ELM_MATH_LOG10: i32 = 21; // log10
pub const ELM_MATH_ANGLE: i32 = 22; // angle
pub const ELM_MATH_TOSTR_BY_CODE: i32 = 23; // tostr_by_code
