pub const ELM_MOUSE_POS_X: i32 = 0;
pub const ELM_MOUSE_WHEEL: i32 = 5;

pub fn is_query_int(elm: i32) -> bool {
    elm == crate::elm::mouse::ELM_MOUSE_POS_X || elm == crate::elm::mouse::ELM_MOUSE_WHEEL
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_MOUSE_POS_Y: i32 = 1; // pos_y
pub const ELM_MOUSE_GET_POS_X: i32 = 2; // get_pos_x
pub const ELM_MOUSE_GET_POS_Y: i32 = 3; // get_pos_y
pub const ELM_MOUSE_CLEAR: i32 = 4; // clear
pub const ELM_MOUSE_RIGHT: i32 = 6; // right
pub const ELM_MOUSE_LEFT: i32 = 7; // left
pub const ELM_MOUSE_NEXT: i32 = 8; // next
pub const ELM_MOUSE_GET_POS: i32 = 9; // get_pos
pub const ELM_MOUSE_SET_POS: i32 = 10; // set_pos
