// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_MOV_PLAY: i32 = 0; // play
pub const ELM_MOV_STOP: i32 = 1; // stop
pub const ELM_MOV_PLAY_WAIT: i32 = 2; // play_wait
pub const ELM_MOV_PLAY_WAIT_KEY: i32 = 3; // play_wait_key
