// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_MSGBK_INSERT_IMG: i32 = 0; // insert_img
pub const ELM_MSGBK_INSERT_MSG: i32 = 1; // insert_msg
pub const ELM_MSGBK_GO_NEXT_MSG: i32 = 2; // go_next_msg
pub const ELM_MSGBK_ADD_MSG: i32 = 3; // add_msg
pub const ELM_MSGBK_ADD_KOE: i32 = 4; // add_koe
pub const ELM_MSGBK_ADD_NAMAE: i32 = 5; // add_namae
