// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_PCMEVENT_START_ONESHOT: i32 = 0; // start_oneshot
pub const ELM_PCMEVENT_START_LOOP: i32 = 1; // start_loop
pub const ELM_PCMEVENT_START_RANDOM: i32 = 2; // start_random
pub const ELM_PCMEVENT_STOP: i32 = 3; // stop
pub const ELM_PCMEVENT_WAIT: i32 = 4; // wait
pub const ELM_PCMEVENT_CHECK: i32 = 5; // check
pub const ELM_PCMEVENT_WAIT_KEY: i32 = 6; // wait_key
