// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_QUAKE_START: i32 = 0; // start
pub const ELM_QUAKE_START_WAIT: i32 = 1; // start_wait
pub const ELM_QUAKE_START_WAIT_KEY: i32 = 2; // start_wait_key
pub const ELM_QUAKE_START_NOWAIT: i32 = 3; // start_nowait
pub const ELM_QUAKE_START_ALL: i32 = 4; // start_all
pub const ELM_QUAKE_START_ALL_WAIT: i32 = 5; // start_all_wait
pub const ELM_QUAKE_START_ALL_WAIT_KEY: i32 = 6; // start_all_wait_key
pub const ELM_QUAKE_START_ALL_NOWAIT: i32 = 7; // start_all_nowait
pub const ELM_QUAKE_END: i32 = 8; // end
pub const ELM_QUAKE_CHECK: i32 = 9; // check
pub const ELM_QUAKE_WAIT: i32 = 10; // wait
pub const ELM_QUAKE_WAIT_KEY: i32 = 11; // wait_key
