pub const ELM_SCRIPT_SET_SKIP_UNREAD_MESSAGE_FLAG: i32 = 74;
pub const ELM_SCRIPT_SET_STAGE_TIME_STOP_FLAG: i32 = 70;

pub fn is_set_int_command(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_SKIP_UNREAD_MESSAGE_FLAG
        || elm == crate::elm::script::ELM_SCRIPT_SET_STAGE_TIME_STOP_FLAG
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_DISABLE
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_ENABLE
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_OFF
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_ON
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_DISP_OFF
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_DISP_ON
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_PROC_OFF
        || elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_PROC_ON
}

pub fn is_set_skip_unread_message_flag(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_SKIP_UNREAD_MESSAGE_FLAG
}

pub fn is_set_msg_back_disable(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_DISABLE
}

pub fn is_set_msg_back_enable(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_ENABLE
}

pub fn is_set_msg_back_on(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_ON
}

pub fn is_set_msg_back_off(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_OFF
}

pub fn is_set_msg_back_disp_off(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_DISP_OFF
}

pub fn is_set_msg_back_disp_on(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_DISP_ON
}

pub fn is_set_msg_back_proc_off(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_PROC_OFF
}

pub fn is_set_msg_back_proc_on(elm: i32) -> bool {
    elm == crate::elm::script::ELM_SCRIPT_SET_MSG_BACK_PROC_ON
}

// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_SCRIPT_START_AUTO_MODE: i32 = 0; // start_auto_mode
pub const ELM_SCRIPT_END_AUTO_MODE: i32 = 1; // end_auto_mode
pub const ELM_SCRIPT_SET_SKIP_DISABLE: i32 = 2; // set_skip_disable
pub const ELM_SCRIPT_SET_MWND_ANIME_OFF_FLAG: i32 = 3; // set_mwnd_anime_off_flag
pub const ELM_SCRIPT_SET_MWND_ANIME_ON_FLAG: i32 = 4; // set_mwnd_anime_on_flag
pub const ELM_SCRIPT_SET_SKIP_ENABLE: i32 = 5; // set_skip_enable
pub const ELM_SCRIPT_SET_CTRL_SKIP_DISABLE: i32 = 6; // set_ctrl_skip_disable
pub const ELM_SCRIPT_SET_CTRL_SKIP_ENABLE: i32 = 7; // set_ctrl_skip_enable
pub const ELM_SCRIPT_SET_MWND_DISP_OFF_FLAG: i32 = 8; // set_mwnd_disp_off_flag
pub const ELM_SCRIPT_GET_MWND_ANIME_OFF_FLAG: i32 = 9; // get_mwnd_anime_off_flag
pub const ELM_SCRIPT_SET_VSYNC_WAIT_OFF_FLAG: i32 = 10; // set_vsync_wait_off_flag
pub const ELM_SCRIPT_SET_QUAKE_STOP_FLAG: i32 = 11; // set_quake_stop_flag
pub const ELM_SCRIPT_SET_MSG_BACK_DISABLE: i32 = 12; // set_msg_back_disable
pub const ELM_SCRIPT_SET_MSG_BACK_ENABLE: i32 = 13; // set_msg_back_enable
pub const ELM_SCRIPT_SET_MOUSE_DISP_OFF: i32 = 14; // set_mouse_disp_off
pub const ELM_SCRIPT_SET_MOUSE_DISP_ON: i32 = 15; // set_mouse_disp_on
pub const ELM_SCRIPT_GET_MWND_ANIME_ON_FLAG: i32 = 16; // get_mwnd_anime_on_flag
pub const ELM_SCRIPT_GET_MWND_DISP_OFF_FLAG: i32 = 17; // get_mwnd_disp_off_flag
pub const ELM_SCRIPT_CHECK_SKIP: i32 = 18; // check_skip
pub const ELM_SCRIPT_SET_MOUSE_MOVE_BY_KEY_DISABLE: i32 = 19; // set_mouse_move_by_key_disable
pub const ELM_SCRIPT_SET_MOUSE_MOVE_BY_KEY_ENABLE: i32 = 20; // set_mouse_move_by_key_enable
pub const ELM_SCRIPT_SET_MSG_ASYNC_MODE_ON: i32 = 21; // set_msg_async_mode_on
pub const ELM_SCRIPT_SET_MSG_ASYNC_MODE_OFF: i32 = 22; // set_msg_async_mode_off
pub const ELM_SCRIPT_GET_QUAKE_STOP_FLAG: i32 = 23; // get_quake_stop_flag
pub const ELM_SCRIPT_GET_VSYNC_WAIT_OFF_FLAG: i32 = 24; // get_vsync_wait_off_flag
pub const ELM_SCRIPT_SET_MESSAGE_SPEED: i32 = 25; // set_message_speed
pub const ELM_SCRIPT_GET_MESSAGE_SPEED: i32 = 26; // get_message_speed
pub const ELM_SCRIPT_SET_MESSAGE_SPEED_DEFAULT: i32 = 27; // set_message_speed_default
pub const ELM_SCRIPT_SET_MESSAGE_NOWAIT_FLAG: i32 = 28; // set_message_nowait_flag
pub const ELM_SCRIPT_GET_MESSAGE_NOWAIT_FLAG: i32 = 29; // get_message_nowait_flag
pub const ELM_SCRIPT_SET_STOP_SKIP_BY_KEY_DISABLE: i32 = 30; // set_stop_skip_by_key_disable
pub const ELM_SCRIPT_SET_STOP_SKIP_BY_KEY_ENABLE: i32 = 31; // set_stop_skip_by_key_enable
pub const ELM_SCRIPT_SET_SHORTCUT_DISABLE: i32 = 32; // set_shortcut_disable
pub const ELM_SCRIPT_SET_SHORTCUT_ENABLE: i32 = 33; // set_shortcut_enable
pub const ELM_SCRIPT_SET_MSG_BACK_OFF: i32 = 34; // set_msg_back_off
pub const ELM_SCRIPT_SET_MSG_BACK_ON: i32 = 35; // set_msg_back_on
pub const ELM_SCRIPT_START_BGMFADE: i32 = 36; // start_bgmfade
pub const ELM_SCRIPT_END_BGMFADE: i32 = 37; // end_bgmfade
pub const ELM_SCRIPT_SET_AUTO_SAVEPOINT_OFF: i32 = 38; // set_auto_savepoint_off
pub const ELM_SCRIPT_SET_AUTO_SAVEPOINT_ON: i32 = 39; // set_auto_savepoint_on
pub const ELM_SCRIPT_SET_KEY_DISABLE: i32 = 40; // set_key_disable
pub const ELM_SCRIPT_SET_KEY_ENABLE: i32 = 41; // set_key_enable
pub const ELM_SCRIPT_SET_KOE_DONT_STOP_ON_FLAG: i32 = 42; // set_koe_dont_stop_on_flag
pub const ELM_SCRIPT_GET_KOE_DONT_STOP_ON_FLAG: i32 = 43; // get_koe_dont_stop_on_flag
pub const ELM_SCRIPT_SET_KOE_DONT_STOP_OFF_FLAG: i32 = 44; // set_koe_dont_stop_off_flag
pub const ELM_SCRIPT_GET_KOE_DONT_STOP_OFF_FLAG: i32 = 45; // get_koe_dont_stop_off_flag
pub const ELM_SCRIPT_SET_HIDE_MWND_DISABLE: i32 = 46; // set_hide_mwnd_disable
pub const ELM_SCRIPT_SET_HIDE_MWND_ENABLE: i32 = 47; // set_hide_mwnd_enable
pub const ELM_SCRIPT_SET_SKIP_TRIGGER: i32 = 48; // set_skip_trigger
pub const ELM_SCRIPT_IGNORE_R_ON: i32 = 49; // ignore_r_on
pub const ELM_SCRIPT_IGNORE_R_OFF: i32 = 50; // ignore_r_off
pub const ELM_SCRIPT_SET_MSG_ASYNC_MODE_ON_ONCE: i32 = 51; // set_msg_async_mode_on_once
pub const ELM_SCRIPT_SET_CURSOR_NO: i32 = 52; // set_cursor_no
pub const ELM_SCRIPT_GET_CURSOR_NO: i32 = 53; // get_cursor_no
pub const ELM_SCRIPT_SET_END_MSG_BY_KEY_DISABLE: i32 = 54; // set_end_msg_by_key_disable
pub const ELM_SCRIPT_SET_END_MSG_BY_KEY_ENABLE: i32 = 55; // set_end_msg_by_key_enable
pub const ELM_SCRIPT_SET_MSG_BACK_DISP_OFF: i32 = 56; // set_msg_back_disp_off
pub const ELM_SCRIPT_SET_MSG_BACK_DISP_ON: i32 = 57; // set_msg_back_disp_on
pub const ELM_SCRIPT_SET_MSG_BACK_PROC_ON: i32 = 58; // set_msg_back_proc_on
pub const ELM_SCRIPT_SET_MSG_BACK_PROC_OFF: i32 = 59; // set_msg_back_proc_off
pub const ELM_SCRIPT_SET_AUTO_MODE_MOJI_WAIT: i32 = 60; // set_auto_mode_moji_wait
pub const ELM_SCRIPT_SET_AUTO_MODE_MIN_WAIT: i32 = 61; // set_auto_mode_min_wait
pub const ELM_SCRIPT_SET_AUTO_MODE_MOJI_WAIT_DEFAULT: i32 = 62; // set_auto_mode_moji_wait_default
pub const ELM_SCRIPT_SET_AUTO_MODE_MIN_WAIT_DEFAULT: i32 = 63; // set_auto_mode_min_wait_default
pub const ELM_SCRIPT_GET_AUTO_MODE_MOJI_WAIT: i32 = 64; // get_auto_mode_moji_wait
pub const ELM_SCRIPT_GET_AUTO_MODE_MIN_WAIT: i32 = 65; // get_auto_mode_min_wait
pub const ELM_SCRIPT_SET_TIME_STOP_FLAG: i32 = 66; // set_time_stop_flag
pub const ELM_SCRIPT_GET_TIME_STOP_FLAG: i32 = 67; // get_time_stop_flag
pub const ELM_SCRIPT_SET_COUNTER_TIME_STOP_FLAG: i32 = 68; // set_counter_time_stop_flag
pub const ELM_SCRIPT_SET_FRAME_ACTION_TIME_STOP_FLAG: i32 = 69; // set_frame_action_time_stop_flag
pub const ELM_SCRIPT_GET_STAGE_TIME_STOP_FLAG: i32 = 71; // get_stage_time_stop_flag
pub const ELM_SCRIPT_GET_FRAME_ACTION_TIME_STOP_FLAG: i32 = 72; // get_frame_action_time_stop_flag
pub const ELM_SCRIPT_GET_COUNTER_TIME_STOP_FLAG: i32 = 73; // get_counter_time_stop_flag
pub const ELM_SCRIPT_GET_SKIP_UNREAD_MESSAGE_FLAG: i32 = 75; // get_skip_unread_message_flag
pub const ELM_SCRIPT_SET_AUTO_MODE_MOJI_CNT: i32 = 76; // set_auto_mode_moji_cnt
pub const ELM_SCRIPT_SET_MOUSE_CURSOR_HIDE_ONOFF: i32 = 77; // set_mouse_cursor_hide_onoff
pub const ELM_SCRIPT_GET_MOUSE_CURSOR_HIDE_ONOFF: i32 = 78; // get_mouse_cursor_hide_onoff
pub const ELM_SCRIPT_SET_MOUSE_CURSOR_HIDE_TIME: i32 = 79; // set_mouse_cursor_hide_time
pub const ELM_SCRIPT_SET_MOUSE_CURSOR_HIDE_TIME_DEFAULT: i32 = 80; // set_mouse_cursor_hide_time_default
pub const ELM_SCRIPT_GET_MOUSE_CURSOR_HIDE_TIME: i32 = 81; // get_mouse_cursor_hide_time
pub const ELM_SCRIPT_SET_MOUSE_CURSOR_HIDE_ONOFF_DEFAULT: i32 = 82; // set_mouse_cursor_hide_onoff_default
pub const ELM_SCRIPT_GET_SKIP_DISABLE_FLAG: i32 = 83; // get_skip_disable_flag
pub const ELM_SCRIPT_GET_CTRL_SKIP_DISABLE_FLAG: i32 = 84; // get_ctrl_skip_disable_flag
pub const ELM_SCRIPT_SET_SKIP_DISABLE_FLAG: i32 = 85; // set_skip_disable_flag
pub const ELM_SCRIPT_SET_CTRL_SKIP_DISABLE_FLAG: i32 = 86; // set_ctrl_skip_disable_flag
pub const ELM_SCRIPT_SET_FONT_NAME: i32 = 87; // set_font_name
pub const ELM_SCRIPT_GET_FONT_NAME: i32 = 88; // get_font_name
pub const ELM_SCRIPT_SET_FONT_NAME_DEFAULT: i32 = 89; // set_font_name_default
pub const ELM_SCRIPT_SET_FONT_BOLD: i32 = 90; // set_font_bold
pub const ELM_SCRIPT_SET_FONT_BOLD_DEFAULT: i32 = 91; // set_font_bold_default
pub const ELM_SCRIPT_GET_FONT_BOLD: i32 = 92; // get_font_bold
pub const ELM_SCRIPT_SET_FONT_SHADOW: i32 = 93; // set_font_shadow
pub const ELM_SCRIPT_SET_FONT_SHADOW_DEFAULT: i32 = 94; // set_font_shadow_default
pub const ELM_SCRIPT_GET_FONT_SHADOW: i32 = 95; // get_font_shadow
pub const ELM_SCRIPT_SET_EMOTE_MOUTH_STOP_FLAG: i32 = 96; // set_emote_mouth_stop_flag
pub const ELM_SCRIPT_GET_EMOTE_MOUTH_STOP_FLAG: i32 = 97; // get_emote_mouth_stop_flag
pub const ELM_SCRIPT_SET_ALLOW_JOYPAD_MODE_ONOFF: i32 = 98; // set_allow_joypad_mode_onoff
pub const ELM_SCRIPT_SET_ALLOW_JOYPAD_MODE_ONOFF_DEFAULT: i32 = 99; // set_allow_joypad_mode_onoff_default
pub const ELM_SCRIPT_GET_ALLOW_JOYPAD_MODE_ONOFF: i32 = 100; // get_allow_joypad_mode_onoff
