// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_SE_PLAY: i32 = 0; // play
pub const ELM_SE_SET_VOLUME: i32 = 1; // set_volume
pub const ELM_SE_SET_VOLUME_MAX: i32 = 2; // set_volume_max
pub const ELM_SE_SET_VOLUME_MIN: i32 = 3; // set_volume_min
pub const ELM_SE_GET_VOLUME: i32 = 4; // get_volume
pub const ELM_SE_PLAY_BY_FILE_NAME: i32 = 5; // play_by_file_name
pub const ELM_SE_PLAY_BY_KOE_NO: i32 = 6; // play_by_koe_no
pub const ELM_SE_STOP: i32 = 7; // stop
pub const ELM_SE_WAIT: i32 = 8; // wait
pub const ELM_SE_PLAY_BY_SE_NO: i32 = 9; // play_by_se_no
pub const ELM_SE_WAIT_KEY: i32 = 10; // wait_key
pub const ELM_SE_CHECK: i32 = 11; // check
