// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_STEAM_SET_ACHIEVEMENT: i32 = 0; // set_achievement
pub const ELM_STEAM_RESET_ALL_STATUS: i32 = 1; // reset_all_status
