// AUTOGENERATED from siglus_scene_script_utility/const.py SYSTEM_ELEMENT_DEFS
pub const ELM_WORLDLIST_ARRAY: i32 = 0; // array
pub const ELM_WORLDLIST_CREATE_WORLD: i32 = 1; // create_world
pub const ELM_WORLDLIST_DESTROY_WORLD: i32 = 2; // destroy_world
